### ISSUE TITLE
Favicon issue

### ISSUE THREAD

**Issue by blindmelon** [urandom/readeef#10]
This a combination of issue and question.

I was wondering why favicons for the feeds come from google (or at least that is what I can work out from the source code).
I've got a few feeds showing with generic "earth" favicons where that is what google returns, and in a couple of cases I just get the word "favicon" (presumably where google returns a 404).

Where a feed provides a channel image, would that make sense to use? If not, what about directly requesting favicon.ico from the host and using that if it exists?

Not a major issue by any means, just a matter of spit and polish.

**Comment by urandom** [comment]
well, its using google because that's the easiest to implement, and it only exists in the client side code.

**Comment by blindmelon** [comment]
Fair enough. As an experiment I tried changing it to fetch from the feeds host /favicon.ico which did give me favicons for the feeds that were missing them, and better ones for some others, but I ended up with even more showing just the alt text than before.

Maybe it would be better to check several sources for a favicon (channel image -> /favicon.ico -> google) and store the image in the database? Then again maybe not.

To carry out my test I ended up editing fs_files.go which has a big DO NOT EDIT warning... where should I have made the change? I couldn't find anywhere else in the code defining the formula (and I haven't got a clue about Go).

By the way, are there many other things being fetched from or sent to google :confused: ?

**Comment by urandom** [comment]
fs_files is the result of running `go generate` in the directory. it just grabs all files listed in `file.list` and puts them in `fs_files.go`.

in order to properly try out your test, you'll need to edit one of the real files (that are in file.list), run `go generate`, and then rebuild the server binary
