### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by klingtnet** [urandom/readeef#11]
I can't login into readeef because of the following error:
`Error: "Error writing session data: mkdir /usr/bin/session: permission denied", type: ` (The whole error message wasn't shown in the login screens error popup)

I'm using `readeef 1.1.0` on Arch Linux. `readeef` is started through systemd with a custom user that, obviously, has no write permission for `/usr/bin` where the executable is located. I'm not sure but it was possible to set the session dir in some previous version.

**Comment by urandom** [comment]
I'll have to look into that. The arch linux packages are still a slight mystery to me

**Comment by klingtnet** [comment]
This seems to be a problem with the  `1.1.0` release that is used in the AUR package. I will close this and #12 for now and try to use it with the latest git master.

**Comment by klingtnet** [comment]
The same error occurs when I use the `go get` version.

**Comment by klingtnet** [comment]
I've added `WorkingDirectory=/tmp` option to the systemd service configuration but this didn't work out either.

**Comment by klingtnet** [comment]
The problem seems to be this line: `https://github.com/urandom/webfw/blob/e64dc14ca68afc46baccc1f7b77156b478f03794/context/session.go#L247`
Why not create the session data inside a temporary directory? Go's `ioutil` provides the [TempDir](https://golang.org/pkg/io/ioutil/#TempDir) function for this purpose.

**Comment by urandom** [comment]
I don't want to automatically put the session data inside /tmp, since ideally you would not want to lose it if your computer restarts (removing /tmp's contents is usually a default behavior then).

However, this is easily configured:
```
[session]
    dir = /tmp
```
Could you put that in your config and see if logging works. If that fixes it, it will probably be better if the default config supplied by the aur package sets this by default, so you can change it to something more appropriate when ready.

**Comment by klingtnet** [comment]
Ah, the webfw.Config is part of readeefs config. This is why I couldn't find the `session` section in the default config: [config.go#L146](https://github.com/urandom/readeef/blob/e34c04dbe0affc4abf6e00691ec80801f20b37c0/config.go#L146). Can you add a note about the webfw config-or better its default config itself-to the default config?

**Comment by klingtnet** [comment]
Setting the session dir did the trick. But I encounter this error #8, too.
I will close this error because the login issue is now fixed.
