### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by prologic** [urandom/readeef#17]
Looks like something broke in recent master;

```
$ readeef server
panic: Cannot provide a repo for driver ''


goroutine 1 [running]:
github.com/urandom/readeef/content/repo/sql.NewService(0x0, 0x0, 0x0, 0x0, 0x5416b80, 0xc4200854f0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/prologic/go/src/github.com/urandom/readeef/content/repo/sql/service.go:42 +0x5f1
main.runServer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/prologic/go/src/github.com/urandom/readeef/cmd/readeef/server.go:99 +0x80f
main.main()
	/Users/prologic/go/src/github.com/urandom/readeef/cmd/readeef/main.go:74 +0x301
```

**Comment by urandom** [comment]
Is it using an existing configuration file? It complains that no sql driver is set up, and the panic itself is the correct behavior here.

**Comment by prologic** [comment]
Its means to use the DefaultCfg defined in source with no config file? At
least this is what the code and README document!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

On Thu, Dec 28, 2017 at 4:45 AM, Viktor Kojouharov <notifications@github.com
