### ISSUE TITLE
dockerfile / docker-compose

### ISSUE THREAD

**Issue by x0rzkov** [urandom/readeef#30]
Hi,

Hope all well for you !

Was wondering if you will dockerize your awesome project with docker-compose and alpine based containers ?

It would be awesome.

Cheers,
X

**Comment by urandom** [comment]
Hi,

I'm all for creating a Dockerfile for it. It should be fairly trivial. I'll try to give it a crack in the coming weeks. Though I'm not personally running it as a container.

**Comment by x0rzkov** [comment]
I started some work on a fork: https://github.com/x0rzkov/readeef

But having issues with vendors with either go.mod or Gopkg.toml while fetching them.

**Comment by urandom** [comment]
i might've been affected by https://github.com/golang/go/issues/29278

i've updated the go.sum file. i should also delete the gopkg ones, since they are unecessary and outdated
