### ISSUE TITLE
Feature request: Export feed opml

### ISSUE THREAD

**Issue by blindmelon** [urandom/readeef#7]
I've been playing around with readeef for a couple of days and I really like it, so I want to set it up a bit more permanently than running it in my homedir with sqlite.

I now have to re-add all my feeds.

readeef can read opml, it would be great if it could also export them.

Thanks for the nice rss reader. I look forward to seeing how things develop.

**Comment by urandom** [comment]
There's now an export button in the Manage feeds section.

**Comment by blindmelon** [comment]
That's great - that means can do something about the database locked errors that I was warned about!
Thanks :+1:
