### ISSUE TITLE
Logging out doesn't work

### ISSUE THREAD

**Issue by blindmelon** [urandom/readeef#8]
I have created multiple users for readeef, but unless I clear the cache etc. I am automatically logged into whichever user I last used, even if I have clicked Logout.

Logging out provides no useful feedback (I get a blank page apart from a header bar at the top with what I assume is a logout symbol), so I don't know if readeef thinks logging out worked or not.

Remembering the last user is fine, but logging out should cause readeef to forget it.

Browser is Firefox 45.0.2

**Comment by klingtnet** [comment]
Even removing the session directory and restart readeef will not kill the session.
